### ISSUE TITLE
Missing RedirectUri on OAuthConnectionInfo

### ISSUE THREAD

**Issue by worthy7** [Jericho/ZoomNet#104]
When I click through the Auth flow, and try to do the first set up for linking a user to my app, 

```
var connectionInfo = new OAuthConnectionInfo(_zoomConfig.ClientId, _zoomConfig.Secret, code,
                (newRefreshToken, newAccessToken) =>
                {
                    refreshToken = newRefreshToken;
                    accessToken = newAccessToken;
                });
```

It returns with a `connectionInfo`, but the access and refresh tokens are not filled in. Is this a bug?

**Comment by worthy7** [comment]
Oh, I get this error if it helps:

> System.Threading.LockRecursionException: Recursive upgradeable lock acquisitions not allowed in this mode.
>    at System.Threading.ReaderWriterLockSlim.TryEnterUpgradeableReadLockCore(TimeoutTracker timeout)
>    at System.Threading.ReaderWriterLockSlim.EnterUpgradeableReadLock()
>    at ZoomNet.Utilities.OAuthTokenHandler.RefreshTokenIfNecessary(Boolean forceRefresh)
>    at ZoomNet.Utilities.OAuthTokenHandler.get_Token()
>    at ZoomNet.Utilities.OAuthTokenHandler.OnRequest(IRequest request)

**Comment by Jericho** [comment]
> It returns with a `connectionInfo`, but the access and refresh tokens are not filled in. Is this a bug?

The tokens are refreshed upon your first request to the Zoom API therefore it's perfectly normal for these two properties to be `null` when you setup the connection info.

> Oh, I get this error if it helps:

Very hard for me to tell what is going on, Please give help me with steps to reproduce this problem.

**Comment by worthy7** [comment]
The steps are just a standard OAuth flow, get the code form the user, send it to zoom to get access tokens, that's all I'm trying to do at this stage.

It seems I am getting a RANDOM error message each time, 1 of 3 things seems to happen when doing this code:
   ```
     public async Task LinkAccountToUser(string code, User u)
        {
            string refreshToken = null;
            string accessToken = null;
            var connectionInfo = new OAuthConnectionInfo(_zoomConfig.ClientId, _zoomConfig.Secret, code,
                (newRefreshToken, newAccessToken) =>
                {
                    refreshToken = newRefreshToken;
                    accessToken = newAccessToken;
                });
            var zoomClient = new ZoomClient(connectionInfo, httpClient: new System.Net.Http.HttpClient());

            // get the user info
            var thisuser = await zoomClient.Users.GetCurrentAsync(CancellationToken.None);
}
```

1) Exception, "Redirect_URI mismatch"
2) Exception System.Threading.LockRecursionException: Recursive upgradeable lock acquisitions not allowed in this mode.
3) Either a very very long dely, or an infinate loop happens somewhere inside `GetCurrentAsync`.

**Comment by Jericho** [comment]
I used the code you provided and I was able to successfully retrieve my user information (the refresh token and the access token were generated in the process, as expected:

![image](https://user-images.githubusercontent.com/112710/108601689-c80e3000-736b-11eb-9316-4b5105628b95.png)
![image](https://user-images.githubusercontent.com/112710/108601775-55ea1b00-736c-11eb-9788-3018383c832c.png)

There has to be something else in your scenario that is causing the three random exceptions.

One detail I want to verify with you: I noticed that an authorization code is used every time your `LinkAccountToUser` method is invoked. This is probably code that you wrote quickly to investigate the problem but I want to confirm that it is clear the authorization codes are intended to be used only once to facilitate the access token and the refresh token to be generated. If you attempt to use authorization codes a second time, Zoom will reject it and throw a `Invalid authorization code` exception. I mention this in the readme because it wasn't clear to me initially and I kept trying to reuse authorization codes which caused me all kinds of grief.

**Comment by worthy7** [comment]
No I fully understand how OAuth works, and this function is how I let a
user connect their zoom account to my app the first time.

Does it matter that I am using dot net core 5?

**Comment by worthy7** [comment]
Regarding the redirect URI, I fixed it by adding it. I have no idea how you guys managed to make it work without it. https://github.com/Jericho/ZoomNet/pull/105

**Comment by Jericho** [comment]
> Does it matter that I am using dot net core 5?

I would be extremely surprised if the framework target in your app had any incidence on Zoom's API throwing an exception about the redirect_uri, but it's worth a try. You should try netcoreapp 3.1 and let me know if you observe anything different

> Maybe it is needed but only when certain scopes are asked for?

That's a pretty good guess. You should try adding/removing some or all of the scopes and let me know if it makes a difference. I tried asking for all scopes in my testing app, but Zoom has a hard limit at 55 scopes. Maybe your app asks for one scope that mine doesn't.

Another possibility may be that you and I could be using different "type" apps. In my case, I created an Account-level app. What type did you create?

![image](https://user-images.githubusercontent.com/112710/108627917-e89ac080-7425-11eb-8793-1a3153cc5da1.png)

I will try to create a user-level app and see if I can make that work. It would be great if you could try switching to a different type and let me know the result.

**Comment by worthy7** [comment]
I am a bit busy right now, but I know it's a user level app

**Comment by Jericho** [comment]
I have created a User-level app which asks for all 22 available scopes and I still can't reproduce the problem you are experiencing. I'm really curious to hear what you find out when you test an account-level app, with different scopes, with different framework target, etc.

Is your app in the Zoom market place? Maybe I could use it for my testing instead of my testing app?

**Comment by worthy7** [comment]
Just in development right now. I can show all my settings though.
[image: image.png]

Did you create a new app btw? Perhaps this was an update to zoom and is a
requirement for new apps only.
I am not sure when I will get time to check out the other settings for you.

**Comment by Jericho** [comment]
I created a new User-level app this morning. My Account-level app was created several months ago, so I have created a brand new one a few minutes ago and tested again, still not able to reproduce the problem.

**Comment by Jericho** [comment]
Whenever you have time to resume investigating the problem you are experiencing, it would probably be helpful if you could capture the http request and response when the problem occurs (in fact, it would be great to have a request-response capture for each of the three problems you randomly experience). My preferred way of capturing http traffic is with a tool called [Fiddler](https://www.telerik.com/download/fiddler). In the Fiddler interface you'll see an "Inspectors" tab that allows you to view requests and responses in various formats. Select the "Raw" format and you'll be able to copy/paste. 
![image](https://user-images.githubusercontent.com/112710/108629460-f81e0780-742d-11eb-9db8-1c92d8780e5c.png)

Make sure you don't paste any sensitive info such as the "Authorization" request header.

**Comment by worthy7** [comment]
FYI: https://devforum.zoom.us/t/trying-to-integrate-not-understanding-the-need-for-the-second-redirect-uri/43833/3

**Comment by Jericho** [comment]
I posted some additional details to your thread on the Zoom forum. Let's see what they say.

In the mean time, 2 things:
1. Have you been able to capture additional debugging info as discussed previously?
2. I figured out a way to get the `Redirect URI mismatch` error from Zoom API: I modified my library's source code to provide a bogus redirect url when converting the auth code into tokens. This results in the following request: `POST https://zoom.us/oauth/token?grant_type=authorization_code&code=CxpyTo4OKw_8lzIwvZTSOqjndWPbPqzuA&redirect_uri=https://this_is_a_bogus_url.com`
and the following response: 
```
HTTP/1.1 403
Content-Length: 79

{"reason":"Invalid request : Redirect URI mismatch.","error":"invalid_request"}
```

But, since the code change is not in my library's publicly released nuget package, I don't think this matches the problem you originally reported (unless you are not using the publicly available nuget package and you made the same modification to my library's source code). Besides, this doesn't explain the other two problem you randomly get.

**Comment by worthy7** [comment]
The redirect issue I assumed was due to no URL being passed. I got fiddler,
that's about as far as it went. I am not sure what I can really do without
spending a lot of time playing with different account configurations to see
if I can make it not require the redirect_uri.

**Comment by Jericho** [comment]
Can you reproduce the problem and capture the raw request/response from Fiddler? That would be a good start.

**Comment by worthy7** [comment]
Ok will try it.

**Comment by Jericho** [comment]
Regarding the intermittent `LockRecursionException`, someone else [reported](#109) the problem and was able to provide steps to reproduce.

**Comment by worthy7** [comment]
@Jericho That's great news. Glad it got sorted. Sorry I couldn't investigate further.

**Comment by Jericho** [comment]
I am also reviewing your PR (thanks for submitting it by the way). I will make a slight modification to it so the RedirectUri can be specified by the developer if desired but not required. This will allow you to specify it, and allow me to omit it. 

It's still a mystery to me why some developers must provide it but not all developers.
