### ISSUE TITLE
New resource: Reports

### ISSUE THREAD

**Issue by Jericho** [Jericho/ZoomNet#11]
Add the reports resource

**Comment by MrSimonC** [comment]
I might make a slow start on this. I've taken over a client in my work where ZoomNet 0.6.0 was being used, then the developer added needed code in his local ZoomNet copy, created a dll, saved only the dll, then didn't save the code (or update this repo)! (then left the company) Lovely.

I might start with <https://marketplace.zoom.us/docs/api-reference/zoom-api/reports/reportmeetingparticipants> since that's what I'll need to allow me to remove his dll. I've other work I need to do first, but I might create a PR in the next few days, unless you've started work on a branch anywhere @Jericho ?

**Comment by Jericho** [comment]
It's really too bad this person didn't contribute his code to this library. 

I'm happy to assign this to you.

**Comment by MrSimonC** [comment]
Hi! Quick update - I've not had time, unfortunately to work on this. I'm also leaving my current job for another company in a fe weeks so someone else might have to pick this up as I'll lose my client's ZoomNet Pro account to login / test with at that point. Maybe work un-assigning me from this. 😄

**Comment by Jericho** [comment]
Thanks for the update and good luck in your new job. I hope we'll have an opportunity to collaborate again in the future.

**Comment by birdbm** [comment]
Hello! I have a branch started with the first method for reports (
/report/meetings/{meetingId}/participants) but I had some questions regarding some of the exception handling and the integration tests.  Should I submit a PR and have a discussion through that or should I ask my questions before that? This will be my first time ever contributing to anything on GitHub and I have zero sense for how things usually work.  By my last question you will also know that I'm more of a junior level developer so bear with me. :)

**Comment by Jericho** [comment]
@birdbm I invite you to read the comments in [this PR](https://github.com/Jericho/ZoomNet/pull/83) because I provided some guidelines to another community member who was contributing for the first time. Some of the comments in that discussion might be interesting to you as well.

Regarding how to discuss your contribution: it's probably easier to create a PR and have discussion through that. I'm guessing a lot of your questions will be something like "method SuchAndSuch doesn't work as I expect", "I'm getting an error on line xxx", etc. These kinds of discussions, in my opinion, are easier when we can review the code in question.
