### ISSUE TITLE
Retry Logic Not Working As Expected

### ISSUE THREAD

**Issue by ninjapiratica** [Jericho/ZoomNet#127]
I don't think the OAuth Token refresh is working as expected. Or rather the retry of the failed request with the new tokens isn't working as expected.

We have tokens that have expired, when we make a new request (such as Users.GetAllAsync()) it fails the call, updates our accessToken and refreshToken and then retries the request. That second request also fails. When we make a new client and use the new tokens, the call works great.

It appears the FluentHttpClient Retry will retry the EXACT request again. So after updating the accessToken and refreshToken, future requests with that client will work, but that request fails, even though it tries to retry it. The update to the tokens in the 'ShouldRetry' method isn't getting applied to that request.

It's time consuming to repro, but it is happening for us every hour that the tokens aren't used. I think the intent was to use the new tokens and immediately retry the request so it will succeed, but it doesn't appear to be working that way.

I'm not very familiar with FluentHttpClient but it seems like the right approach is to implement an IRequestCoordinator instead of an IRetryConfig, as it gives access to the request as well, (hopefully it can be modified).

**Comment by Jericho** [comment]
Don't worry about providing a repro. Your description of the problem is clear and sufficient for me to stat investigating. It's obvious, based on your description of the problem, that you thoroughly investigated the problem before raising this issue. I greatly appreciate that.

Your suggestion to use a custom `IRequestCoordinator` is actually how ZoomNet worked until version 0.25.0. FluentHttpClient (which is an OSS project I contribute to) introduced a new feature about a month ago that allows configuring multiple IRetryConfig and I was able to get rid of our custom coordinator in favor of the new built-in functionality in version 0.26.0. What I failed to realize is that it would cause the request to be retried without using the newly refreshed token.

In the short term you can revert to ZoomNet 0.25.0 while I figure out how I can force the retry request to use the newly refreshed token (or revert to the custom retry coordinator). I know this is not an ideal solution for you because you need to be able to page the result of the User.GetAllAsync method and this functionality did not work properly until 0.27.0 but I am offering this workaround anyway so you are not stuck while I research a solution.

**Comment by ninjapiratica** [comment]
Thanks. If there is something you think I can do to help contribute, let me know. I'd be glad to help out in some way.

**Comment by Jericho** [comment]
I have published a release candidate with a fix [here](https://www.myget.org/feed/jericho/package/nuget/ZoomNet/0.27.2-rc0001). I am waiting for my own token to expire in order to validate that the retry is correctly using the newly refreshed token.
