### ISSUE TITLE
Survey: which .Net framework should ZoomNet support?

### ISSUE THREAD

**Issue by Jericho** [Jericho/ZoomNet#133]
ZoomNet currently targets net461, net472, netstandard2.0 and net5.0 but I'm wondering if we could completely drop support for "full" framework (i.e. net461 and net472)? Is that too disruptive though? Is anybody still using the "full" framework? Maybe replacing these two targets with net48 would be a less disruptive approach?

As far as .NET "core", Microsoft has dropped support for 2.0 in October 2018 and 2.1 is the current version under "long term support (see here). Support for 2.0 ended about 2 and a half years ago so I am pretty confident that developers had enough time to upgrade by now.

I'm trying to strike a balance between supporting the greatest number of developers (no matter which version of the .NET they target) and getting rid of older, unsupported versions of .NET.

What I'm thinking about doing is:

remove net461, net472 and replace them with net48
remove netstandard2.0 and replace it with netstandard2.1

Here's an [interesting article](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/) on this topic.

Let me know what you think. I'm looking forward for your feedback.

**Comment by MrSimonC** [comment]
Hello! Thought I'd add a comment for context. Right now I work for [Felinesoft Ltd](http://felinesoft.com/) (at least for the next 3 weeks anyway!). We have clients using a Microsoft Dynamics / Api / Umbraco set up. Both Dynamics and Umbraco are very very early stages in terms of .net core / .net 5. Also, since our work is governed by the client, rather than ourselves, the tendency is to stick to .net framework solutions and not upgrade tech debt in favour of new features. We use ZoomNet in one of my clients and at least one other of the companies - both in the API layer on (and i've just checked) on framework v4.6.2.
Personally i'm new all the way - .net 5, then  .net 6 this november, and would always favour this _but_ often the decision is taken out of my hands.

Counter argument: On yet another project I work on, this was not using Zoom, but was on .net 4.5.0. A feature i needed was on v4.5.2 but i decided that if we're to update anything, I would update it to v4.8 - which is still backwards compatible, _so_ I think there has to be a middle ground - Microsoft are now moving all their app service runtimes to .net framework v4.8, and deprecating lower versions - and we know that our old (client) code will run on that. Since software development is always moving forward, I'd support (even with my company's clients) targeting just a single version of .net framework - v4.8 since this is the pattern i'm seeing Microsoft moving to.

**Comment by Jericho** [comment]
Thank you for the in-depth feedback. I realize that we will not be able to get rid of the full framework for quite a whilebut at the same time, you are cementing my resolve to update ZoomNet to net4.8.
