### ISSUE TITLE
ZoomRooms Issues and Issues ZoomRooms API endpoints are not working correctly

### ISSUE THREAD

**Issue by vesuvian** [Jericho/ZoomNet#136]
I've addresses the problems in this PR https://github.com/Jericho/ZoomNet/pull/135

1. I was getting bad feedback from the room issues API endpoints because of bad JsonProperties, so I fixed those
2. Some of the properties were badly named so I corrected them
3. I understand the decision to represent the IssueType as an enum, but I'm concerned about Zoom eventually adding new values, changing existing values, or even implementing localization. I elected to remove the IssueType enum and instead use a string, but I'll understand if you want this part reverted.

**Comment by Jericho** [comment]
> 1. I was getting bad feedback from the room issues API endpoints because of bad JsonProperties, so I fixed those

Excellent.

> 2. Some of the properties were badly named so I corrected them

Good catch. Thanks for fixing my typos and copy-paste mistakes.

> 3. I understand the decision to represent the IssueType as an enum, but I'm concerned about Zoom eventually adding new values, changing existing values, or even implementing localization. I elected to remove the IssueType enum and instead use a string, but I'll understand if you want this part reverted.

I thought long and hard about this one. Generally speaking, I prefer an enum because you get intellisense and if you need to write logic based on the type of issue, you don't have to compare strings. What ultimately nudged me in favor of an enum is that Zoom extensively documented all the possible values so I felt it was safe to create an enum. Of course we'll need to modify our enum if/when Zoom decides to add a new value, delete an existing value or update a value but the same risk exist with any of the enum types that we created in ZoomNet so I'm not too nervous about this risk. However, you make a good point that my reasoning falls apart if they ever decide to localize this string. Do you have any indication that they intend to do that?

**Comment by vesuvian** [comment]
No indication at all, just programmer brain being overly defensive.

I've read and understood all of your comments on both of my PRs. Next time I get a chance (maybe next week at this rate?) I'll clean everything up and submit that third PR for you. Thank you!
