### ISSUE TITLE
Random issue in Http429RetryStrategy.GetDelay

### ISSUE THREAD

**Issue by Julie-House** [Jericho/ZoomNet#151]
Hi,
I hate to log this without definitive repo steps but I really don't know where to start with this one! A client is unable to use our Zoom integration because the call to Users.GetAllAsync is failing with a very strange error
` System.NullReferenceException: Object reference not set to an instance of an object. at ZoomNet.Utilities.Http429RetryStrategy.GetDelay(Int32 attempt, HttpResponseMessage response) at ZoomNet.Utilities.ZoomRetryCoordinator.<ExecuteAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Pathoschild.Http.Client.Internal.Request.<Execute>d__43.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Pathoschild.Http.Client.Internal.Request.<AsMessage>d__34.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at ZoomNet.Internal.<AsObject>d__61.MoveNext()`

The really random thing though is that on my development system, I can use the clients details and the full list of users is returned as expected. On the clients system, using our dev credentials it also works perfectly. On our demo system it also works with our dev credentials but not the clients credentials. 

I can't see how this can be related to the credentials when it works for me, but it also can't be environmental as their system works with our credentials! The whole thing makes no sense. I've even tried Postman at the client site and it correctly returns data for their credentials so it can't be an issue talking to Zoom. Any ideas with where I can go with this?!

Many thanks

**Comment by Jericho** [comment]
`Http429RetryStrategy` is involved when the Zoom API returns a HTTP 429 code in the response which means that too many requests have been issued in a given period of time. The Users.GetAll Zoom API is [documented](https://marketplace.zoom.us/docs/api-reference/zoom-api/users/users) as being on a "medium" rate limit which translates to 30 requests per second according to [this](https://marketplace.zoom.us/docs/api-reference/rate-limits#account-rate-limits). 

So my first thought is that you haven't been able to reproduce this problem in PostMan probably because you issue only one request at a time and this problem only occurs more requests than allowed by Zoom API.

Also: `Http429RetryStrategy.GetDelay` attempts to calculate a reasonable delay to wait before automatically reissuing the same request in order to overcome the "too many requests" problem. It does so by inspecting the headers returned by the Zoom API as described [here](https://marketplace.zoom.us/docs/api-reference/rate-limits#error-handling-best-practices). Specifically, we are looking for the following headers:
```
X-RateLimit-Category
X-RateLimit-Type
X-RateLimit-Limit
X-RateLimit-Remaining
Retry-After
```

So, my second thought: maybe for some reason these expected header are missing? This would be unusual and unexpected but maybe something in your client's infrastructure (such as a proxy server for example) is stripping headers that are not on an "approved" list. I know what I just said sounds completely ludicrous but I have experienced it myself. Back in my consulting days, I was doing web development for a client who had a policy of removing headers from HTTP responses unless they had been previously "approved". This client felt it was a safe practice to remove headers but of course they didn't mention it to us and we wasted a lot of time investigating why our application didn't behave as expected. Anyway, long story short: this may or may not be the situation at your client, but I just thought I would mention it because this painful experience is seared in my memory all those years later.

Having said this, I took care to ensure that ZoomNet's retry logic would be resilient even when expected HTTP headers are missing but maybe I missed something. Maybe there's a line of code that assume a given header is always present. I will review the code and let you know if I find any logic that could be improved.

**Comment by Jericho** [comment]
For reference, here's what a typical HTTP 429 response from the Zoom API looks like:

![image](https://user-images.githubusercontent.com/112710/140084425-35f8b18d-55e1-4951-aee7-3dc6b204f022.png)

Notice the presence of the `X-RateLimit-...` headers.

**Comment by Jericho** [comment]
The only theoretical flaw in the `GetDelay` logic I can see is that I made the assumption that either the `Retry-After` header is present (which tells us precisely how long to wait before automatically re-issuing the request that triggered the HTTP429 response) **OR** the response contains the `X-RateLimit-Type: QPS` header which allows us to assume that it's reasonable to wait for about a second. However, this logic fails to account for the possibility that both headers could be absent from the response. This doesn't seem like a possible scenario (based on my understanding of Zoom's documentation on the subject) but your experience seems to indicate that it is indeed a possibility.

The only way for me to validate if this is the case is if you could capture the HTTP 429 response and post it here.

**Comment by Jericho** [comment]
Actually, instead of waiting for you to provide a capture of a HTTP 429 response I figured I could simulate the scenario where all the expected headers are missing by modifying the ZoomNet library to deliberately removing them, like so:

```csharp
foreach (var header in response.Headers)
{
    if (header.Key.StartsWith("X-RateLimit-") || header.Key == "Retry-After")
    {
        response.Headers.Remove(header.Key);
    }
}
```

When the `GetDelay` method is subsequently invoked I witness a NullReference exception, just like you described. This proves that ZoomNet currently does not handle scenarios where all the rate limit headers are missing but it doesn't explain **WHY** they are missing. It could be specific to your client's environment, it could be an undocumented scenario with the Zoom API that I have never witnessed before, it could be documented but I misread (or misinterpreted) the documentation. Who knows!?!?!?  Do you have any insight? I am genuinely intrigued and would love to figure this out.

In the mean time, I will work on an update to handle this scenario. I can't promise I will be able to get to it today or tomorrow but certainly before the end of the week.

**Comment by Julie-House** [comment]
Thanks so much for looking into this. When I use Postman on my machine, I can only see one header out of those listed which is X-RateLimit-Category (set to Medium). I will get my guy to check what he see's either on his demo system or the clients system if he can. I suspect we might have to wait a while though as I know he gets busy!

The only other thing i would note is that we have just 3 users in our account. But, the clients has lots. We are making the call with 300 in the hopes that we don't have to deal with paging. I'm wondering if that might somehow have something to do with it too. When we tried in Postman at their site we used the default of 30. I have already asked that he increase this to 300 to see if that fails and gives us something else to go on. 
![image](https://user-images.githubusercontent.com/66947692/140098466-4c3b354e-3997-4b80-9cbc-40ed9ca9f6b5.png)

**Comment by Jericho** [comment]
> I can only see one header out of those listed which is X-RateLimit-Category (set to Medium)

You can see the rate limit category but not the type or the "retry-after"???!?!? That's very intriguing. Please note that Fiddler (I'm assuming Postman is similar) does not list headers in alphabetical order so sometimes they are not next to each other which makes it easy to overlook them.

**Comment by Julie-House** [comment]
I've got 24 headers, most of them are `Set-Cookie`. No `Retry-After`. other than the other x ones listed in that screenshot, the only other custom header is `x-zm-trackingid`....

**Comment by Julie-House** [comment]
My guy got back to me. same deal, 24 headers and no `Retry-After`
![zoom all users1](https://user-images.githubusercontent.com/66947692/140163146-3d15a949-efc0-444b-aa1b-14d458019765.jpg)
![zoom all users2](https://user-images.githubusercontent.com/66947692/140163152-f012e844-004a-4f66-9b38-0b5bf3eb0fd4.jpg)
I can't use Fiddler (it interferes with our VPN) so I can't check the headers on the call made by our software but I would assume they are the same. But we're back to it not making any sense, because it works for me but not the client, where apparently everything is the same!

**Comment by Julie-House** [comment]
Ok, just read about the rate limiting stuff. You only get the Retry-After when you get the 429. In the case of Postman we're not getting a 429 so everything is fine. If I can produce some sort of test dll which can print out the raw Zoom response we might be able to get somewhere. I'll have a look tomorrow and see what I can think up.

**Comment by Jericho** [comment]
The screenshot you posted indicates that the response is HTTP 200:

![image](https://user-images.githubusercontent.com/112710/140190302-9ede3e49-b853-4916-bd5a-8b96c47b0205.png)

This whole time we have been talking about HTTP 429 so that's not representative of the problem we are investigating.

Does postman have a way to issue a given request a certain number of times? In Fiddler, for example, you can highlight a given request, hold the Shift key and push the R key and you get the following prompt:
![image](https://user-images.githubusercontent.com/112710/140190926-e3b3f402-b8fe-4c00-a3d8-db45a4914d5f.png)

**Comment by Jericho** [comment]
Published a release candidate of ZoomNet that can handle missing "rate limit" headers on [my MyGetFeed](https://www.myget.org/feed/jericho/package/nuget/ZoomNet/0.35.0-rc0000). Let me know if you have a chance to give it a try and whether it indeed solves the problem your client is experiencing.

**Comment by Julie-House** [comment]
Right - fresh head. Was wondering why the call works in Postman but not in our app. The issue is down to Zoom. We need to know specifically just the users that have the Webinar permission. (We actually need those users with the Webinar Setting but misunderstood Zoom so are looking up the permissions). Either way, you can't find that information out with a call to list users. You have to inquire about each individual user and get their permissions (or settings) separately. So we loop through all the users returned, ignoring Basic users, and create a new item in our list, kicking off a new async task for each user to get their permissions. The client has 256 users...

One thing we can look at is caching the users so this process doesn't happen too frequently. But working out if we can kick this off in the background somewhere is going to be more complicated. I could work in a delay after every 20 users or something like that, but this could then mean the call which is already slow, becomes too slow. I'll have a think what we can do here. I think ultimately this area needs a rethink when you have more than a small handful of users...

Thanks so much for looking into this though. Clearly there's still some sort of issue with the header going missing. I'll see what i can do regarding getting your fix into a test for the client.

**Comment by Jericho** [comment]
@Julie-House do you have any feedback?

**Comment by Julie-House** [comment]
@Jericho Sorry. Unfortunately you and I have a sense of urgency and curiousness about this... My implementation guy does not! I've heard nothing. I provided the new dll to him with instructions but nothing has been done.

In terms of long-term solving this issue. I'm going to change the code so our config area allows the users to select the roles which contain the relevant users i.e. those with webinar capabilities. From there we can get the list of users and not have to get their settings/permissions. It's frustrating that Zoom doesn't provide the settings as part of the whole user object. Our integration is for webinars only so we need to make sure we limit the users we handle. 

Thanks so much for looking into this though! I wouldn't have figured it out otherwise :)

**Comment by Julie-House** [comment]
@Jericho Good News! It works :) Finally pushed my guy into testing it today, once he realised it was a simple dll swap he tried it and it works perfectly. Not sure what's causing the headers to go walkies but your fix has solved it.

If you push that to main I'll get our project properly updated just in time for our next release. I shall pass on my guys message to you as really it's for you not me... he said 'you are such a legend!!!!'

**Comment by Jericho** [comment]
I am closing this issue so that I can move forward with including this fix with the next release but I encourage you to add comments if you find additional information.

In particular, do you think we will ever be able to take a look at a capture of a HTTP 429 response?
