### ISSUE TITLE
Better handle cases where HTTP200 indicates failure

### ISSUE THREAD

**Issue by Jericho** [Jericho/ZoomNet#159]
@michael-aj-kennedy found approximately half a dozen scenarios where, as incredible as it may seem, HTTP 200 does not indicate success but rather that the developer is lacking permissions to accomplish the desired action. I'm sure there are other similar scenarios that we haven't discovered yet.

Currently we have some boiler plate code that we copy and paste in every resource method that corresponds to one of those scenarios (here's an [example](https://github.com/Jericho/ZoomNet/blob/b1bec39f5c83721fa6817492a1188324b908f840/Source/ZoomNet/Resources/Webinars.cs#L237)).

I think it would make sense to eliminate the need to copy/paste the boilerplate code and handle these scenarios in a consistent manner. One way to accomplish this would be to add a parameter to all the `AsObject`, `AsPaginatedResponse`, `AsPaginatedResponseWithToken`, etc. methods (something like `bool http200IndicatesLackofPermissions = false`). We simply would need to specify a `true` value in the aforementioned scenarios.

**Comment by michael-aj-kennedy** [comment]
I'd agree with this, far more elegant than coding handling of the response type on a function-by-function basis.  

It's worthwhile noting that Zoom doesn't just use 200 responses to indicate a lack of permissions, there are a few subtle differences between calls, I've seen functions which will return 200 responses if:

- The user isn't running a paid account (webinar functionality).
- The user doesn't have the necessary access rights (creating/updating roles).
- The object being deleted didn't exist (attempting to delete a role that doesn't exist explicitly returns a 200 status).

While I disagree with Zoom's usage of the 200 response entirely, I almost understand their approach with that last one, but there might be some scenario where a developer cares about the difference.

I wonder if rather than passing in a boolean value it might be worth using an enumerated type just so that ZoomNet can throw a more specific error message - we already have three specific situations where a 200 response doesn't necessarily indicate success, who's to say that there won't be more?

**Comment by Jericho** [comment]
I see your point.

Scratch my previous suggestion, I have a much more elegant solution that will allow us to specify that we want HTTP 200 to be treated as a failure and also to specify a custom error message if desired. Something like this:

```csharp
return _client
	.PatchAsync($"roles/{id}")
	.WithJsonBody(data)
	.WithHttp200TreatedAsFailure("The account must be a paid account to update the role.")
	.WithCancellationToken(cancellationToken)
	.AsMessage();
```

I'll work on a proof-of-concept this weekend.
