### ISSUE TITLE
Dashboard Participant additional fields

### ISSUE THREAD

**Issue by birdbm** [Jericho/ZoomNet#167]
It looks like when you get DashboardParticipants (whether they be meeting participants or webinar participants), you can get the field for role in the Zoom API.   I'm not seeing that in any of the models and was curious if I was missing something or if it wasn't there.   The reason I'm asking is specifically related to panelists in Webinars.  The role isn't included when you use the List Participants under Webinars AND under Webinars if you use List Panelists you can only pass in the Webinar Id instead of the Uuid.  I think the DashboardWebinarParticipants endpoint is the only way to get the panelists for a given Uuid.  I can probably add it this weekend (it's easy!), but just wanted to double check that I wasn't missing something.       

https://marketplace.zoom.us/docs/api-reference/zoom-api/methods#operation/dashboardMeetingParticipants

![image](https://user-images.githubusercontent.com/97680941/151637095-5e2f0c6b-9239-46fc-86dd-cfbffd2be37a.png)

**Comment by Jericho** [comment]
The "Dashboard" resource was added to ZoomNet in September 2020 (shoutout to @M-Zuber for [his contribution](https://github.com/Jericho/ZoomNet/pull/48)) and it looks like Zoom has made some changes to the fields returned from the API since then. That explains why you are seeing fields in the documentation that are not present in ZoomNet.

I reviewed the documentation this morninig and, in addition to the `role` field you already identified, I found a few more fields that have ben added to the meeting/webinar participants dashboard API:
- `full_data_center`
- `registrant_id`
- `audio_quality`
- `video_quality`
- `screen_share_quality`
- `customer_key`
- `sip_uri`
- `from_sip_uri`

I also found 2 additional fields returned when querying for meeting participants (they are not returned when querying for webinar participants):
- `participant_user_id`
- `status`

**Comment by Jericho** [comment]
@birdbm I uploaded a [beta version](https://www.myget.org/feed/jericho/package/nuget/ZoomNet/0.38.0-dashboard-partic0020) of ZoomNet with the additional fields to my MyGet feed. Can you try it out and give me some feedback before I release?

**Comment by birdbm** [comment]
I will try it out here shortly! Thank you!

**Comment by birdbm** [comment]
@Jericho that breaks the endpoint.  Looks like a minor issue with the enumeration.  

![image](https://user-images.githubusercontent.com/97680941/151714307-9dac8986-b645-4cab-af29-e235aeb4a793.png)

**Comment by Jericho** [comment]
My bad: I totally missed the "Others" enum item. Gve me 30 minutes or so and I'll have another beta on MyGet.

**Comment by Jericho** [comment]
Done. New beta available: https://www.myget.org/feed/jericho/package/nuget/ZoomNet/0.38.0-dashboard-partic0021

**Comment by birdbm** [comment]
@Jericho that worked really well!  I was able to see all the fields you mentioned for Webinars.

**Comment by Jericho** [comment]
Excellent. Thank you for the feedback. I will prepare release notes and publish to NuGet later tonight.
