### ISSUE TITLE
Webinar panelist coming back as attendee

### ISSUE THREAD

**Issue by JBlakeMCAA** [Jericho/ZoomNet#194]
First off thank you so much for making everyone's life easier :)
I think I found a issue:
When returning "GetWebinarParticipantsAsync(webinarID)"
"foreach (DashboardParticipant Participant in response.Result.Records)"
is coming back "Participant.Role" as panelist  when they are attendee and visa versa.

**Comment by Jericho** [comment]
I'm very glad this library is making your life easier, thank you for the kind words!

The `Role` property on the `DashboardParticipant` is a string and its value simply comes from the `role` node in the JSON returned from the Zoom API. Therefore, as far as I can tell, if this property contains "panelist" or "attendee", it's because that's what is returned from the Zoom API.

You can validate what I just said by looking at the JSON returned from the Zoom API and double-check if it indeed contains something like `"role":"participant"`. The easiest way, in my opinion, to capture the JSON is to use a tool such as [Fiddler](https://www.telerik.com/fiddler). There are many other tools out there but Fiddler is my personal favorite, I highly recommend it.

Feel free to post the JSON string that you capture with Fiddler in a comment below, and I will be happy to review it.

**Comment by Jericho** [comment]
To demonstrate my point, take a look at [this unit test](https://github.com/Jericho/ZoomNet/blob/develop/Source/ZoomNet.UnitTests/Models/DashboardParticipant.cs#L48) (and in particular the last assertion). It shows that the "role" in the JSON is deserialized into the expected string value.

**Comment by JBlakeMCAA** [comment]
Thank you so much for looking into this.
I exported a report from Zoom and debugged the results from my code...I don't see where I am making a mistake but I'll look further to see, if you see anything let me know.
See attached image of report results.

https://masonrybuyersguide.com/Capture.JPG

```

       #region GET_WEBINAR_PARTICIPANTS
        public static void GET_WEBINAR_PARTICIPANTS
            (
            string Webinar_webinarId
            )
        {

            try
            {
                //Get list of Participant
                var response = GetWebinarParticipantsAsync(Webinar_webinarId);
                response.Wait();

                if (response == null) { return; }

                //Each Participant
                foreach (DashboardParticipant Participant in response.Result.Records)
                {

                    if (Participant == null) { continue; }

                    Debug.WriteLine($"Role: {Participant.Role} Person {Participant.UserName}");

                }
            }
            catch (Exception e)
            {
                Debug.WriteLine("Exception ERROR:" + e.Message);
            }
         }
```

**Comment by Jericho** [comment]
Have you captured the JSON returned from the Zoom API? This will give you the definitive answer to whether you are getting the data you expect or not. And, as I mentioned earlier, I will be happy to review this JSON if you post it here (or a subset of it if it's exceedingly large).

**Comment by Jericho** [comment]
@JBlakeMCAA are you still investigating? Will you be sharing additional info so I can help you or should we just close this issue?

**Comment by Zealouseappex** [comment]
I apologize for the delay, I will be able to get a report later this week when I get back to the office.

**Comment by Jericho** [comment]
Haven't heard from you in a while and you haven't provided any additional information that would allow investigating further. Can I assume this is no longer a concern?

**Comment by JBlakeMCAA** [comment]
Hi Jericho,
I found out it was an issue on our end so sorry for the delay.
