### ISSUE TITLE
[Question] How to create a Meeting with an invitee list?

### ISSUE THREAD

**Issue by Crul** [Jericho/ZoomNet#236]
Looking at [the Zoom docs for the Create Meeting endpoint](https://marketplace.zoom.us/docs/api-reference/zoom-api/methods/#operation/meetingCreate), I see the property `settings.meeting_invitees` but I cannot find it on the C# class `ZoomNet.Models.MeetingSettings`.

Am I missing something? Thanks!

**Comment by Jericho** [comment]
Zoom's model changes constantly, it's hard to keep up. If you notice something missing, I invite you to submit a PR. That would help tremendously.

In the mean time, you can invoke `Meetings.InviteParticipantsAsync` after you have created the meeting. It's two calls instead of a single call but the result is the same.

**Comment by Crul** [comment]
@Jericho Understood, thanks!

Currently I cannot use ZoomNet because we need to upgrade our project to a more recent version of .NET core. When we do that I will take a look into the change.

Closing the issue / question.
Thanks again!
