### ISSUE TITLE
Parsing response takes a very long time

### ISSUE THREAD

**Issue by BrianWhiting** [Jericho/ZoomNet#371]
In my attempt to upgrade from 0.80.0 to 0.81.0, I noticed that calling `client.CloudRecordings.GetRecordingsForUserAsync` seemed to never return for certain users with a lot of recordings.

I was able to track down the issue to the new method `ZoomNet.Internal.ParseZoomResponseAsync`, specifically line 951 where it tries to do match a regular expression, https://github.com/Jericho/ZoomNet/blob/9ebcc67cedf38cd7206bd9743538e999c7b7f219/Source/ZoomNet/Extensions/Internal.cs#L951.

The regular expression takes longer and longer to execute as the number of recordings in the response grows. On my development machine, for 5 recordings, it takes less than 1 second, 10 recordings takes about 4 seconds to complete, and 15 recordings takes around 10 seconds.

**Comment by Jericho** [comment]
> 15 recordings takes around 10 seconds.
Yikes. That's not acceptable.

The reason this regex was added in 0.81.0 is to workaround a bug in the Zoom API: the response to some of our requests is malformed due to double quotes that are not properly escaped which prevents us from parsing the payload into a JSON document. I reported the issue to Zoom and I was told the following:

> I have created a request internally to fix this issue (ZOOM-789295), and while we are trying to fix it, here is an example logic in js on how you can handle this issue at your end:

They proceeded to show me a JavaScript code sample with regex to detect and fix un-escaped double-quotes. The code you saw in the `ParseZoomResponseAsync` method is my C# interpretation of the JavaScript code they shared with me.

Either way, it's not an excuse to slow the parsing of the response to the extend that you have observed.

I will figure out a way to improve the parsing speed.

**Comment by BrianWhiting** [comment]
I have verified that the issue appears to be fixed with your 0.82.0-alpha.7 build. No apparent slowdown when the response contains 90 recordings.

**Comment by Jericho** [comment]
Excellent. Thank you for confirming. I'm waiting on a contributor to confirm #367. As soon as I hear back from him I will publish 0.82.0 to Nuget.

**Comment by Jericho** [comment]
Contributor confirmed functionality introduced in #367 therefore I'm proceeding with the release.
