### ISSUE TITLE
Don't use redirect_url in Request Access Token

### ISSUE THREAD

**Issue by AndrewKatast** [Jericho/ZoomNet#61]
Don't use redirect_url in Request Access Token

**Comment by Jericho** [comment]
I'm not sure I understand what you are trying to say. Can you expand?

**Comment by AndrewKatast** [comment]
https://marketplace.zoom.us/docs/guides/auth/oauth

We need to use "redirect_url" in Step 2: Request Access Token

in OAuthTokenHandler method  RefreshTokenIfNecessary 
You don't add redirect_url  in case - OAuthGrantType.AuthorizationCode.

FYI: Thanks for  great library.

**Comment by Jericho** [comment]
> We need to use "redirect_url" in Step 2: Request Access Token

The `redirect_uri` is for scenarios where you are interactively directing users to Zoom for authentication and you need Zoom to redirect the user to your web app when they are successfully authenticated. This does not apply to the typical scenario for this library which is typically used for "server-to-server" authentication. 

But maybe you have a special scenario in mind that I haven't thought of. Can you expand on your scenario?

> FYI: Thanks for great library.

You are welcome and I am glad you find it useful.

**Comment by Jericho** [comment]
Do you want to continue this discussion?

**Comment by AndrewKatast** [comment]
Yea, you are right, we use it in .net core web application.
I find a way to use your library in these app. All i need , connect your client after i  got access token.

**Comment by worthy7** [comment]
@Jericho Actually I understand and have this issue now.

For some reason, which I myself do not understand (maybe just security?) Zoom seems to want us to send the `redirect_uri` a SECOND time, when requesting the access/refresh tokens (from the auth code).

You can see here the first time (getting user to log in and then redirecting back to your server) 
https://marketplace.zoom.us/docs/guides/auth/oauth#getting-access-token

Then for some reason the server needs to also include it here:
![image](https://user-images.githubusercontent.com/4762399/108583841-d0706600-737f-11eb-9dd9-053fab2484f9.png)


I do not know why, I guess just to confirm. But this client doesn't see to send this right? In fact I am struggling to understand what this package is even doing in that regard. Should blank work? If zoom requires the redirect_uri again when converting code -> tokens, how do I supply it in this package? how does it work?

**Comment by Jericho** [comment]
> For some reason, which I myself do not understand (maybe just security?) Zoom seems to want us to send the `redirect_uri` a SECOND time, when requesting the access/refresh tokens (from the auth code).

hummmm. I agree that the verbiage in `Step 2: Request Access Token` in the documentation you linked makes it sound like we need to provide the redirect_uri. However, I have never provided it and I can complete the whole OAuth flow without any problem. Also, I know other developers use ZoomNet successfully to authenticate using OAuth so I am a little skeptical that this is really required.

> I do not know why, I guess just to confirm. But this client doesn't see to send this right? In fact I am struggling to understand what this package is even doing in that regard. Should blank work? If zoom requires the redirect_uri again when converting code -> tokens, how do I supply it in this package? how does it work?

Correct, ZoomNet does not send the 'redirect_uri' and everything works perfectly for myself and, as far as I know, it also works for other developers as well.

You raised a separate issue where you mention that you randomly get exceptions when trying to complete the OAuth flow and one of these exceptions is `Redirect_URI mismatch` which probably is the reason why you started investigating whether ZoomNet provides the redirect_uri. I suggest we continue our investigation on that other issue rather than on this issue that has been closed for several months. Makes sense?
